spring:
  application:
    name: eureka-server
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka